name: Pipery Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pipery-tooling
        run: pip install git+https://github.com/pipery-dev/pipery-tooling.git
      - name: Test action
        run: pipery-actions test --repo .
